from __future__ import annotations


def build_help_text() -> str:
    return (
        "ARC Raiders Events Bot\n"
        "\n"
        "Commands:\n"
        "/start - open the interactive inline menu\n"
        "/menu - open the interactive inline menu\n"
        "/events - show compact event summary grouped by event type\n"
        "/events map <map name> - filter grouped event summary by map\n"
        "/events event <event name> - filter grouped event summary by event\n"
        "/watch all - subscribe to all events\n"
        "/watch map <map name> - subscribe to a map\n"
        "/watch event <event name> - subscribe to an event\n"
        "/watch event <event name> | map <map name> - subscribe to an event on a map\n"
        "/unwatch all - remove all subscriptions\n"
        "/unwatch map <map name> - remove a map subscription\n"
        "/unwatch event <event name> - remove an event subscription\n"
        "/unwatch event <event name> | map <map name> - remove a combined subscription\n"
        "/notify <minutes...> - replace notification offsets\n"
        "/notify add <minutes...> - add notification offsets\n"
        "/notify remove <minutes...> - remove notification offsets\n"
        "/notify list - show current notification offsets\n"
        "/list - show subscriptions and notification offsets\n"
        "/maps - show maps catalog\n"
        "/events_catalog - show events catalog\n"
        "/help - show this help\n"
        "\n"
        "Menu shortcuts:\n"
        "- Subscribe to an event\n"
        "- Unsubscribe from one subscription or all subscriptions\n"
        "- Configure notification offsets with buttons or manual input\n"
        "- Open the full schedule or a single event schedule\n"
        "- Show current subscriptions and notification offsets\n"
        "\n"
        "Names are human-readable and case-insensitive.\n"
        "/events shows the current run or nearest upcoming run plus up to 3 future runs for each event.\n"
        "If both event and map are used in one command, separate them with `|`.\n"
        "\n"
        "Examples:\n"
        "/events map Space port\n"
        "/watch event Meteor shower | map Blue gate\n"
        "/notify 30 15 5"
    )
